name: Tests using Jest
on:
  pull_request:
     branches:
        - dev-test
jobs:
   run-tests:
      runs-on: ubuntu-latest
      steps:
         - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
         - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
         - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
         - name: Prettify code
           uses: creyD/prettier_action@v3.3
         - name: Install deps
           uses: actions/checkout@v2
         - run: npm install --legacy-peer-deps --silent
         - run: npm install --save-dev prettier pretty-quick --silent
         - run: npm test
